apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testnnnn
  janus-idp.io/tekton: testnnnn
  backstage.io/kubernetes-id: testnnnn
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testnnnn
resources: 
- deployment.yaml
- route.yaml
- service.yaml
