apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testnnnn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnnnn 
  name: testnnnn
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: testnnnn 
